-- 2026-08-18 · Módulo RCA — cumplimiento de compromisos ambientales (RCA)
-- Sistema AM · Antofagasta Minerals
--
-- Una RCA (Resolución de Calificación Ambiental) compromete que un % del gasto
-- de cada empresa colaboradora (EECC) sea con proveedores LOCALES/REGIONALES.
-- Seguimiento:
--   · Cada EECC declara por CARTA FORMAL un monto total a gastar en el proyecto.
--   · La meta es el pct_meta% (10% por defecto) de ese monto declarado.
--   · Las EECC envían mes a mes un Excel con sus facturas de compra.
--   · Se cruza el RUT de cada factura contra rca_proveedores_validados. Solo las
--     facturas de proveedores REGIONALES validados suman al avance del 10%.
--   · Un RUT que no está en el registro dispara una ALERTA de revisión manual.
--
-- RLS en el mismo cambio (CLAUDE.md Regla 3). Acceso: slug 'rca' o 'principal'.
-- El registro de validados se siembra con los 137 proveedores del Excel oficial
-- "BD Provedores" (Planillas CMZ): 121 regionales, 16 fuera de región.

create table if not exists public.rca_normativas (
  rca_id text primary key,
  codigo text not null,
  nombre text,
  faena text,
  descripcion text,
  texto_compromiso text,
  pct_meta numeric not null default 10,
  estado text default 'activa',
  estado_registro text default 'Activo',
  created_by text, updated_by text,
  created_at timestamptz default now(), updated_at timestamptz default now()
);

create table if not exists public.rca_eecc (
  eecc_id text primary key,
  rca_id text not null references public.rca_normativas(rca_id),
  nombre text not null,
  rut text,
  contacto_nombre text, contacto_fono text, contacto_correo text,
  numero_contrato text, administrador text,
  monto_declarado numeric default 0,
  moneda text default 'CLP',
  carta_path text, carta_nombre text, carta_fecha date,
  fecha_desde date, fecha_hasta date,
  notas text,
  estado_registro text default 'Activo',
  created_by text, updated_by text,
  created_at timestamptz default now(), updated_at timestamptz default now()
);

create table if not exists public.rca_proveedores_validados (
  rvp_id bigint generated always as identity primary key,
  rut text unique not null,
  razon_social text,
  comuna text,
  clasificacion text,
  bien_servicio text,
  region text,
  es_regional boolean default false,
  validado boolean default true,
  validado_por text, validado_en timestamptz default now(),
  notas text,
  estado_registro text default 'Activo',
  created_by text, updated_by text,
  created_at timestamptz default now(), updated_at timestamptz default now()
);

create table if not exists public.rca_facturas (
  factura_id text primary key,
  rca_id text not null references public.rca_normativas(rca_id),
  eecc_id text not null references public.rca_eecc(eecc_id),
  anio text, mes text,
  num_factura text,
  eecc_nombre text,
  rut_proveedor text,
  razon_social text,
  comuna text,
  bien_servicio text,
  clasificacion text,
  monto_clp numeric default 0,
  monto_usd numeric default 0,
  rvp_id bigint references public.rca_proveedores_validados(rvp_id),
  es_regional boolean default false,
  estado_revision text default 'pendiente',
  origen text default 'excel',
  estado_registro text default 'Activo',
  created_by text, updated_by text,
  created_at timestamptz default now(), updated_at timestamptz default now()
);

create index if not exists idx_rca_eecc_rca on public.rca_eecc(rca_id);
create index if not exists idx_rca_facturas_rca on public.rca_facturas(rca_id);
create index if not exists idx_rca_facturas_eecc on public.rca_facturas(eecc_id);
create index if not exists idx_rca_facturas_rut on public.rca_facturas(rut_proveedor);
create index if not exists idx_rvp_rut on public.rca_proveedores_validados(rut);

alter table public.rca_normativas            enable row level security;
alter table public.rca_eecc                   enable row level security;
alter table public.rca_proveedores_validados  enable row level security;
alter table public.rca_facturas               enable row level security;

do $$
declare t text;
begin
  foreach t in array array['rca_normativas','rca_eecc','rca_proveedores_validados','rca_facturas'] loop
    execute format('drop policy if exists %I_rw on public.%I', t, t);
    execute format('create policy %I_rw on public.%I for all to authenticated using (tiene_acceso(''rca'') or es_principal()) with check (tiene_acceso(''rca'') or es_principal())', t, t);
  end loop;
end $$;

insert into public.rca_proveedores_validados
  (rut, razon_social, comuna, clasificacion, bien_servicio, region, es_regional)
values
('76604002-0','ALOJAMIENTOS NORTE LIMITADA','ANTOFAGASTA','ALOJAMIENTO / HOTEL','SERVICIOS','Antofagasta',true),
('76052649-5','ALTO DEL SOL S.A.','ANTOFAGASTA','ALOJAMIENTO / HOTEL','SERVICIOS','Antofagasta',true),
('76039285-5','ARRIENDO DE EQUIPOS Y SERVICIOS TIRREAU Y COMPANIA LIMITADA','ANTOFAGASTA','ARRIENDO EQUIPO / MAQUINARIA','SERVICIOS','Antofagasta',true),
('77239832-8','BARRIOS VERA INGENIEROS SOCIEDAD POR ACCIONES','ANTOFAGASTA','OBRAS CIVILES / SERVICIOS VARIOS / MAESTRANZA','SERVICIOS','Antofagasta',true),
('76053153-7','C.A SERVICIOS SPA','ANTOFAGASTA','ARRIENDO EQUIPO / MAQUINARIA','SERVICIOS','Antofagasta',true),
('76036872-5','CAPACITACIÓN INTEGRAL ATACAMA LIMITADA','ANTOFAGASTA','CAPACITACIONES','SERVICIOS','Antofagasta',true),
('76184576-4','CENTRO MEDICO LABORAL PAUL EHRLICH LIMITADA','ANTOFAGASTA','LABORATORIO / CENTRO MEDICO','SERVICIOS','Antofagasta',true),
('77920000-0','COMERCIAL SERVIREP LIMITADA','ANTOFAGASTA','ARRIENDO EQUIPO / MAQUINARIA','SERVICIOS','Antofagasta',true),
('77851810-4','CONSTRUCTORA Y HORMIGONES COPAT NORTE LIMITADA','ANTOFAGASTA','MATERIAL DE CONSTRUCCIÓN / FERRETERÍA / REPUESTOS MAQUINAS','BIENES','Antofagasta',true),
('76430143-9','CORSSEN SPA','ANTOFAGASTA','ARRIENDO EQUIPO / MAQUINARIA','SERVICIOS','Antofagasta',true),
('76623461-5','DIMECPRO INGENIERIA SPA','ANTOFAGASTA','OBRAS CIVILES / SERVICIOS VARIOS / MAESTRANZA','SERVICIOS','Antofagasta',true),
('76356183-6','DIPROFIRE CHILE LTDA.','ANTOFAGASTA','INCENDIO / CCTV / EXTINTORES / SEGURIDAD','BIENES','Antofagasta',true),
('77580065-8','DTD CHILE SPA','ANTOFAGASTA','ARRIENDO EQUIPO / MAQUINARIA','SERVICIOS','Antofagasta',true),
('76809012-2','FABRICACION Y SERVICIOS ADRIANA MARIA CORTES PEREZ E.I.R.L.','ANTOFAGASTA','OBRAS CIVILES / SERVICIOS VARIOS / MAESTRANZA','SERVICIOS','Antofagasta',true),
('76892554-2','FAST RENT ANTOFAGASTA SPA','ANTOFAGASTA','MANTENCIÓN O ARRIENDO DE VEHICULOS','SERVICIOS','Antofagasta',true),
('77593260-0','IMPORTACIONES Y REPRESENTACIONES BOX SOLUTION LTDA','ANTOFAGASTA','MATERIAL DE CONSTRUCCIÓN / FERRETERÍA / REPUESTOS MAQUINAS','BIENES','Antofagasta',true),
('77875772-9','INDUSTRIALPIZMAN SPA','ANTOFAGASTA','MATERIAL DE CONSTRUCCIÓN / FERRETERÍA / REPUESTOS MAQUINAS','BIENES','Antofagasta',true),
('76455680-1','INGEMARS INGENIERIA LIMITADA','ANTOFAGASTA','LABORATORIO / CENTRO MEDICO','SERVICIOS','Antofagasta',true),
('99526550-8','INGENIERIA Y MONTAJE FERROVIAL S.A.','ANTOFAGASTA','ARRIENDO EQUIPO / MAQUINARIA','SERVICIOS','Antofagasta',true),
('12630241-K','JANET DEL CARMEN MIRANDA MIRANDA','ANTOFAGASTA','MATERIAL DE CONSTRUCCIÓN / FERRETERÍA / REPUESTOS MAQUINAS','BIENES','Antofagasta',true),
('8467524-5','JANET MARIANELLA FARIAS AHUMADA','ANTOFAGASTA','MATERIAL DE CONSTRUCCIÓN / FERRETERÍA / REPUESTOS MAQUINAS','BIENES','Antofagasta',true),
('77512538-1','JCG VENTAS Y SERVICIOS SPA','ANTOFAGASTA','MATERIAL DE CONSTRUCCIÓN / FERRETERÍA / REPUESTOS MAQUINAS','BIENES','Antofagasta',true),
('76998495-K','M2D INGENIERIA Y CONSTRUCCION SPA','ANTOFAGASTA','RESTAURANTE / ALIMENTACIÓN EN FAENA / ALIMENTOS Y BEBIDAS','SERVICIOS','Antofagasta',true),
('77427242-9','MOTORS360 SPA','ANTOFAGASTA','MANTENCIÓN O ARRIENDO DE VEHICULOS','SERVICIOS','Antofagasta',true),
('77621758-1','MRC SOLUTIONS SPA','ANTOFAGASTA','TRANSPORTE PERSONAL / TRANSPORTE DE CARGAS','SERVICIOS','Antofagasta',true),
('77621487-6','NORTE ARRIENDA SPA','ANTOFAGASTA','ARRIENDO EQUIPO / MAQUINARIA','SERVICIOS','Antofagasta',true),
('77123419-4','PHCES PIEZAS PREFABRICADAS DE HORMIGÓN LIMITADA','ANTOFAGASTA','MATERIAL DE CONSTRUCCIÓN / FERRETERÍA / REPUESTOS MAQUINAS','BIENES','Antofagasta',true),
('77663678-9','PROIND SPA SPA','ANTOFAGASTA','INSUMOS OFICINA / IMPRENTA / PUBLICIDAD','BIENES','Antofagasta',true),
('77659197-1','PULSO SALUD CHILE SPA','ANTOFAGASTA','LABORATORIO / CENTRO MEDICO','SERVICIOS','Antofagasta',true),
('96924780-1','RELIPER COMERCIAL LTDA.','ANTOFAGASTA','MATERIAL DE CONSTRUCCIÓN / FERRETERÍA / REPUESTOS MAQUINAS','BIENES','Antofagasta',true),
('77979940-9','REVESTIMIENTOS ARQUITECTÓNICOS E INDUSTRIALES LIMITADA','ANTOFAGASTA','MATERIAL DE CONSTRUCCIÓN / FERRETERÍA / REPUESTOS MAQUINAS','BIENES','Antofagasta',true),
('77687190-7','SOC SANCHEZ LABARCA LIMITADA','ANTOFAGASTA','INSUMOS OFICINA / IMPRENTA / PUBLICIDAD','BIENES','Antofagasta',true),
('77701531-1','SOCIEDAD COMERCIAL SAYANI SPA','ANTOFAGASTA','TRANSPORTE PERSONAL / TRANSPORTE DE CARGAS','SERVICIOS','Antofagasta',true),
('76106479-7','SOCIEDAD DE TRANSPORTE DE CARGA Y PERSONAL IRCO COMPANIA LIMITADA','ANTOFAGASTA','TRANSPORTE PERSONAL / TRANSPORTE DE CARGAS','BIENES','Antofagasta',true),
('77543436-8','T Y M. WINNER TRANSPORTE Y MANTENCIÓN SPA','ANTOFAGASTA','MANTENCIÓN O ARRIENDO DE VEHICULOS','SERVICIOS','Antofagasta',true),
('76354001-4','TRANSPORTES Y SERVICIOS VÍCTOR HUGO MORENO OYARCE EMPRESA INDIVIDUAL D','ANTOFAGASTA','TRANSPORTE PERSONAL / TRANSPORTE DE CARGAS','SERVICIOS','Antofagasta',true),
('76509755-K','VILLA Y VILLA SPA','ANTOFAGASTA','MATERIAL DE CONSTRUCCIÓN / FERRETERÍA / REPUESTOS MAQUINAS','BIENES','Antofagasta',true),
('76465760-8','COMERCIALIZADORA FERNORTE INDUSTRIAL LIMITADA','ANTOFAGASTA','MATERIAL DE CONSTRUCCIÓN / FERRETERÍA / REPUESTOS MAQUINAS','BIENES','Antofagasta',true),
('76759109-8','FERRETERIA ZAVALA HNOS. SPA','ANTOFAGASTA','MATERIAL DE CONSTRUCCIÓN / FERRETERÍA / REPUESTOS MAQUINAS','BIENES','Antofagasta',true),
('76104876-7','FLUINORT LIMITADA','ANTOFAGASTA','MATERIAL DE CONSTRUCCIÓN / FERRETERÍA / REPUESTOS MAQUINAS','BIENES','Antofagasta',true),
('76529132-1','HORMIDAT CONSTRUCCION Y OBRAS CIVILES SPA','ANTOFAGASTA','MATERIAL DE CONSTRUCCIÓN / FERRETERÍA / REPUESTOS MAQUINAS','BIENES','Antofagasta',true),
('77505182-5','HORMIGÓN PREFABRICADO OPENCAST LIMITADA','ANTOFAGASTA','MATERIAL DE CONSTRUCCIÓN / FERRETERÍA / REPUESTOS MAQUINAS','BIENES','Antofagasta',true),
('76473475-0','IGMA ANTOFAGASTA SPA','ANTOFAGASTA','MATERIAL DE CONSTRUCCIÓN / FERRETERÍA / REPUESTOS MAQUINAS','BIENES','Antofagasta',true),
('76696269-6','NORTHTEK INGENIERÍA LIMITADA','ANTOFAGASTA','OBRAS CIVILES / SERVICIOS VARIOS / MAESTRANZA','SERVICIOS','Antofagasta',true),
('76100301-1','PEREZ, MARTIN Y COMPANIA LIMITADA','ANTOFAGASTA','MATERIAL DE CONSTRUCCIÓN / FERRETERÍA / REPUESTOS MAQUINAS','BIENES','Antofagasta',true),
('77095437-1','TRANSPORTES Y SERVICIOS MARCOS MURAÑA SALINAS E.I.R.L.','ANTOFAGASTA','ARRIENDO EQUIPO / MAQUINARIA','SERVICIOS','Antofagasta',true),
('79751470-5','SOC COMERCIAL SAN ANDRES LIMITADA','ANTOFAGASTA','MATERIAL DE CONSTRUCCIÓN / FERRETERÍA / REPUESTOS MAQUINAS','BIENES','Antofagasta',true),
('76982397-2','INGENIERÍA ERR SPA','ANTOFAGASTA','TRANSPORTE PERSONAL / TRANSPORTE DE CARGAS','BIENES','Antofagasta',true),
('15690107-5','EXEQUIEL ALEJANDRO OLIVARES ROJAS','ANTOFAGASTA','TRANSPORTE PERSONAL / TRANSPORTE DE CARGAS','SERVICIOS','Antofagasta',true),
('77837927-9','MAXBAL SPA','ANTOFAGASTA','MATERIAL DE CONSTRUCCIÓN / FERRETERÍA / REPUESTOS MAQUINAS','BIENES','Antofagasta',true),
('77089004-7','FERRETERÍA IVETTE GRIMANESA SAEZ DIAZ E.I.R.L','ANTOFAGASTA','MATERIAL DE CONSTRUCCIÓN / FERRETERÍA / REPUESTOS MAQUINAS','BIENES','Antofagasta',true),
('96884900-K','HOTEL ANTOFAGASTA SPA','ANTOFAGASTA','ALOJAMIENTO / HOTEL','SERVICIOS','Antofagasta',true),
('77351417-8','SERVICIOS INTEGRALES DE LOGÍSTICA Y TRANSPORTE DE CARGA LOGISPRO SPA','ANTOFAGASTA','TRANSPORTE PERSONAL / TRANSPORTE DE CARGAS','SERVICIOS','Antofagasta',true),
('76452898-0','NORTERRA MAQUINARIAS SPA','ANTOFAGASTA','MATERIAL DE CONSTRUCCIÓN / FERRETERÍA / REPUESTOS MAQUINAS','SERVICIOS','Antofagasta',true),
('76061055-0','DOMO COMERCIAL E INDUSTRIAL LTDA.','ANTOFAGASTA','OBRAS CIVILES / SERVICIOS VARIOS / MAESTRANZA','SERVICIOS','Antofagasta',true),
('76049267-1','MC ARRIENDOS Y SERVICIOS INTEGRALES LTDA','ANTOFAGASTA','ARRIENDO EQUIPO / MAQUINARIA','SERVICIOS','Antofagasta',true),
('77992522-6','SERVILAV INDUSTRIAL NORTE SPA','ANTOFAGASTA','LAVANDERÍA / SERVICIOS DE LIMPIEZA','SERVICIOS','Antofagasta',true),
('76016979-K','TECNOLOGIAS EN MAQUINARIAS DE TERMOFUSION LIMITADA','ANTOFAGASTA','OBRAS CIVILES / SERVICIOS VARIOS / MAESTRANZA','SERVICIOS','Antofagasta',true),
('8522997-4','ALDO FRANQUI PIZARRO ARAYA','CALAMA','CAPACITACIONES','SERVICIOS','Antofagasta',true),
('10935218-7','ALEJANDRO MOISES ARRIAGADA HUERTA','CALAMA','TRANSPORTE PERSONAL / TRANSPORTE DE CARGAS','SERVICIOS','Antofagasta',true),
('76998845-9','ARRIENDO DE MAQUINARIA TRANSAQM SPA','CALAMA','MATERIAL DE CONSTRUCCIÓN / FERRETERÍA / REPUESTOS MAQUINAS','BIENES','Antofagasta',true),
('76867880-4','CID INVERSIONES SPA','CALAMA','ALOJAMIENTO / HOTEL','SERVICIOS','Antofagasta',true),
('13172409-8','CLAUDIA ALEJANDRA VARELA MOLINA','CALAMA','ALOJAMIENTO / HOTEL','SERVICIOS','Antofagasta',true),
('78543960-0','COMERCIAL FERNANDEZ Y CIA LTDA','CALAMA','MATERIAL DE CONSTRUCCIÓN / FERRETERÍA / REPUESTOS MAQUINAS','BIENES','Antofagasta',true),
('76593731-0','CONSTRUCTORA CERRO JARDÍN LIMITADA','CALAMA','ARRIENDO EQUIPO / MAQUINARIA','SERVICIOS','Antofagasta',true),
('77254520-7','CONSTRUCTORA Y HORMIGON COPAT LTDA','CALAMA','MATERIAL DE CONSTRUCCIÓN / FERRETERÍA / REPUESTOS MAQUINAS','BIENES','Antofagasta',true),
('76784373-9','COPMAM SERVICE LIMITADA','CALAMA','ALOJAMIENTO / HOTEL','SERVICIOS','Antofagasta',true),
('76087283-0','EMPRESA DE PRESTACIÓN DE SERVICIOS DE FERRETERÍA','CALAMA','MATERIAL DE CONSTRUCCIÓN / FERRETERÍA / REPUESTOS MAQUINAS','BIENES','Antofagasta',true),
('76181127-4','FERRETERIA CALAMA SOCIEDAD POR ACCIONES','CALAMA','MATERIAL DE CONSTRUCCIÓN / FERRETERÍA / REPUESTOS MAQUINAS','BIENES','Antofagasta',true),
('76334112-7','FERRETERÍA INDUSTRIAL, VENTAS, ARRIENDOS E INSUMOS FERREMINER SPA','CALAMA','MATERIAL DE CONSTRUCCIÓN / FERRETERÍA / REPUESTOS MAQUINAS','BIENES','Antofagasta',true),
('77180052-1','FERRETERIA MARIA CAROLINA MOYA GONZALEZ EMPRESA INDIVIDUAL DE RESPO','CALAMA','MATERIAL DE CONSTRUCCIÓN / FERRETERÍA / REPUESTOS MAQUINAS','BIENES','Antofagasta',true),
('9821227-2','HERMAN JAVIER RIVERA CHACANA','CALAMA','COMBUSTIBLES','BIENES','Antofagasta',true),
('9474171-8','HERNAN ENRIQUE FONSECA ILLANES','CALAMA','COMBUSTIBLES','BIENES','Antofagasta',true),
('76184456-3','IMASER SPA','CALAMA','MATERIAL DE CONSTRUCCIÓN / FERRETERÍA / REPUESTOS MAQUINAS','BIENES','Antofagasta',true),
('76691919-7','INNOVACAP CAPACITACIONES SPA','CALAMA','CAPACITACIONES','SERVICIOS','Antofagasta',true),
('77010669-9','INVERSIONES INTEGRALES SAN ANDRES SPA','CALAMA','MATERIAL DE CONSTRUCCIÓN / FERRETERÍA / REPUESTOS MAQUINAS','BIENES','Antofagasta',true),
('77403136-7','J&M SERVICE SPA','CALAMA','INSUMOS OFICINA / IMPRENTA / PUBLICIDAD','BIENES','Antofagasta',true),
('8280125-1','JACQUELINE MIRIAM LARRAGUIBEL VALENCIA','CALAMA','MATERIAL DE CONSTRUCCIÓN / FERRETERÍA / REPUESTOS MAQUINAS','BIENES','Antofagasta',true),
('9986467-2','JAVIER JAIME ROJAS VEGA','CALAMA','MATERIAL DE CONSTRUCCIÓN / FERRETERÍA / REPUESTOS MAQUINAS','BIENES','Antofagasta',true),
('8672186-4','JORGE GUILLERMO GARECA OTAROLA','CALAMA','INSUMOS OFICINA / IMPRENTA / PUBLICIDAD','BIENES','Antofagasta',true),
('10229111-5','JULIO ERNESTO ARAYA ARAYA','CALAMA','ALOJAMIENTO / HOTEL','SERVICIOS','Antofagasta',true),
('12125820-K','LUIS ALBERTO QUIROZ GAETE','CALAMA','TRANSPORTE PERSONAL / TRANSPORTE DE CARGAS','SERVICIOS','Antofagasta',true),
('76101036-0','LUIS ALEJANDRO LOPEZ ALDAY LAVANDERÍA Y ASEO INDUSTRIAL Y TRANSPORTE DE PERSONAL (Larimar)','CALAMA','LAVANDERÍA / SERVICIOS DE LIMPIEZA','SERVICIOS','Antofagasta',true),
('77536555-2','MUÑOZ Y MONCADA LIMITADA','CALAMA','ALOJAMIENTO / HOTEL','SERVICIOS','Antofagasta',true),
('77899962-5','OASIS-VIDA EDGARDO ENRIQUE RIVERA TORRES E.I.R.L.','CALAMA','RESTAURANTE / ALIMENTACIÓN EN FAENA / ALIMENTOS Y BEBIDAS','SERVICIOS','Antofagasta',true),
('76761591-4','OBRAS HIDRAULICAS MINERIA Y VIALIDAD SPA','CALAMA','ARRIENDO EQUIPO / MAQUINARIA','SERVICIOS','Antofagasta',true),
('9615180-2','OSCAR ANTONIO NUÑEZ LAVADO','CALAMA','INCENDIO / CCTV / EXTINTORES / SEGURIDAD','BIENES','Antofagasta',true),
('77516059-4','PREFABRICADOS RAFAEL PERALES SPA','CALAMA','MATERIAL DE CONSTRUCCIÓN / FERRETERÍA / REPUESTOS MAQUINAS','BIENES','Antofagasta',true),
('76604968-0','SERVICIOS DE CONSTRUCCION Y RENTA EQUIPOS SPA','CALAMA','ARRIENDO EQUIPO / MAQUINARIA','SERVICIOS','Antofagasta',true),
('77139936-3','SOCIEDAD AMERICA LIMITADA','CALAMA','MATERIAL DE CONSTRUCCIÓN / FERRETERÍA / REPUESTOS MAQUINAS','BIENES','Antofagasta',true),
('76978773-9','SOCIEDAD COMERCIAL ADA CORTES E HIJOS LIMITADA','CALAMA','ALOJAMIENTO / HOTEL','SERVICIOS','Antofagasta',true),
('76631632-8','SOCIEDAD COMERCIAL ESCALERA Y DÍAZ LIMITADA','CALAMA','MANTENCIÓN O ARRIENDO DE VEHICULOS','SERVICIOS','Antofagasta',true),
('77083864-9','SPEEDGRAFF SPA','CALAMA','INSUMOS OFICINA / IMPRENTA / PUBLICIDAD','BIENES','Antofagasta',true),
('77043058-5','TRANS TURBO CHILE SPA','CALAMA','TRANSPORTE PERSONAL / TRANSPORTE DE CARGAS','BIENES','Antofagasta',true),
('77481495-7','TRANSILVER SPA','CALAMA','TRANSPORTE PERSONAL / TRANSPORTE DE CARGAS','SERVICIOS','Antofagasta',true),
('76232934-4','TRANSPORTES AMIGO SPA','CALAMA','TRANSPORTE PERSONAL / TRANSPORTE DE CARGAS','SERVICIOS','Antofagasta',true),
('76659969-9','TRANSPORTES DANYXA POLLYANNA RODRIGUEZ ALFARO EMPRESA INDIVIDUAL DE R','CALAMA','TRANSPORTE PERSONAL / TRANSPORTE DE CARGAS','SERVICIOS','Antofagasta',true),
('76545605-3','TRANSPORTES PULLMAN YURIS LIMITADA','CALAMA','TRANSPORTE PERSONAL / TRANSPORTE DE CARGAS','SERVICIOS','Antofagasta',true),
('77694881-0','TRANSPORTES Y SERVICIOS BCM SPA','CALAMA','ARRIENDO EQUIPO / MAQUINARIA','SERVICIOS','Antofagasta',true),
('76429200-6','UBERLINDA OVANDO CALAMA SPA','CALAMA','MATERIAL DE CONSTRUCCIÓN / FERRETERÍA / REPUESTOS MAQUINAS','BIENES','Antofagasta',true),
('76520488-7','VIALGRAFIC LTDA','CALAMA','INSUMOS OFICINA / IMPRENTA / PUBLICIDAD','BIENES','Antofagasta',true),
('76587159-K','BERMAQ SPA','CALAMA','MATERIAL DE CONSTRUCCIÓN / FERRETERÍA / REPUESTOS MAQUINAS','BIENES','Antofagasta',true),
('76861748-1','MULTISERVICIO EMMANUEL SPA','CALAMA','ARRIENDO EQUIPO / MAQUINARIA','SERVICIOS','Antofagasta',true),
('77649313-9','L&R INGENIERIA Y CLIMATIZACIÓN SPA','CALAMA','MATERIAL DE CONSTRUCCIÓN / FERRETERÍA / REPUESTOS MAQUINAS','BIENES','Antofagasta',true),
('77039080-K','ARAYA BRIONES LIMITADA','CALAMA','INSUMOS OFICINA / IMPRENTA / PUBLICIDAD','BIENES','Antofagasta',true),
('77428694-2','GRAFIMINER SPA','CALAMA','INSUMOS OFICINA / IMPRENTA / PUBLICIDAD','BIENES','Antofagasta',true),
('77510000-1','MAESTRANZA, CONSTRUCCION Y SERVICIOS A LA MINERIA FARIAS LTDA','CALAMA','OBRAS CIVILES / SERVICIOS VARIOS / MAESTRANZA','SERVICIOS','Antofagasta',true),
('76592566-5','ALTO DEL SOL CALAMA SPA','CALAMA','ALOJAMIENTO / HOTEL','SERVICIOS','Antofagasta',true),
('76380238-8','SOCIEDAD DE TRANSPORTES Y MAQUINARIAS GODOY-GODOY LIMITADA','CALAMA','RESTAURANTE / ALIMENTACIÓN EN FAENA / ALIMENTOS Y BEBIDAS','SERVICIOS','Antofagasta',true),
('7424118-2','SERGIO HERNAN BRIBBO ALVAREZ','MEJILLONES','RESTAURANTE / ALIMENTACIÓN EN FAENA / ALIMENTOS Y BEBIDAS','SERVICIOS','Antofagasta',true),
('15871396-9','JOSE LUIS ANDRADE QUINONES','MEJILLONES','RESTAURANTE / ALIMENTACIÓN EN FAENA / ALIMENTOS Y BEBIDAS','SERVICIOS','Antofagasta',true),
('77199033-9','INGENIERÍA Y CONSTRUCCIÓN JRAG SPA','MEJILLONES','OBRAS CIVILES / SERVICIOS VARIOS / MAESTRANZA','SERVICIOS','Antofagasta',true),
('96789280-7','CIA PORTUARIA MEJILLONES S A','MEJILLONES','PUERTO','SERVICIOS','Antofagasta',true),
('76029874-3','HOTELERA COSTA DEL SOL-MEJILLONES','MEJILLONES','ALOJAMIENTO / HOTEL','SERVICIOS','Antofagasta',true),
('78502770-1','BUSES J M PULLMAN S A (Santiago)','OTRO','','',NULL,false),
('76453928-1','CYA EVENTOS SPA (Iquique)','OTRO','','',NULL,false),
('76855960-0','EMPRESAS GARRIDO CACERES LIMITADA (SANTIAGO)','OTRO','','',NULL,false),
('76651103-1','HOJALATERIA Y CLINICA DEL HOGAR LIMITADA (VIÑA)','OTRO','','',NULL,false),
('76748276-0','HOSTAL RICARDO ESTEBAN CARVAJAL ESPINOZA E.I.R.L. (VALPARAÍSO)','OTRO','','',NULL,false),
('78449070-K','LABORATORIO CLINICO ARAUCO LTDA (Iquique)','OTRO','','',NULL,false),
('92177000-6','LAVANDERÍA LE GRAND CHIC SPA (SANTIAGO)','OTRO','','',NULL,false),
('12497623-5','MARCELO HERMOGENES FUENZALIDA CRISOSTOMO (COLINA)','OTRO','','',NULL,false),
('18978606-9','RICHARD PATRICIO CALABRAN VERA (BIO BIO)','OTRO','','',NULL,false),
('77003950-9','SOLUCIONES MODULARES Y ESTRUCTURALES LTDA (COLINA)','OTRO','','',NULL,false),
('76613610-9','IGMA COMERCIAL SPA (La Cisterna Santiago)','OTRO','','',NULL,false),
('77501904-2','MAESTRANZA BARK SPA (SANTIAGO)','OTRO','','',NULL,false),
('96048000-7','PETRICIO INDUSTRIAL SA','OTRO','','',NULL,false),
('76116435-K','SOCIEDAD COMERCIAL E INVERSIONES LEO LOA S.A','OTRO','','',NULL,false),
('77530009-4','SOCIEDAD COMERCIAL J.P. LIMITADA (ñUBLE)','OTRO','','',NULL,false),
('96523950-2','SOC INVERSIONES CALAMA S A','OTRO','','',NULL,false),
('77639681-8','CISTANTHE SPA','SIERRA GORDA','ALOJAMIENTO / HOTEL','SERVICIOS','Antofagasta',true),
('17831015-1','Hector Ariel Rivera Hernández (La Casona)','SIERRA GORDA','RESTAURANTE / ALIMENTACIÓN EN FAENA / ALIMENTOS Y BEBIDAS','SERVICIOS','Antofagasta',true),
('76193727-8','INMOBILIARIA HOTELERA Y TURISMO CAMPO DUNAR LIMITADA','SIERRA GORDA','ALOJAMIENTO / HOTEL','SERVICIOS','Antofagasta',true),
('76644994-8','RESTAURANT MARIA CASTILLO PEREZ E.I.R.L. (Keryma)','SIERRA GORDA','RESTAURANTE / ALIMENTACIÓN EN FAENA / ALIMENTOS Y BEBIDAS','SERVICIOS','Antofagasta',true),
('11617324-7','GUSTAVO EDUARDO ALVAREZ SEGOVIA','TALTAL','TRANSPORTE PERSONAL / TRANSPORTE DE CARGAS','SERVICIOS','Antofagasta',true),
('77518873-1','CONSTRUCTORA - HORMIGONES - EQUIPOS MONTECRISTO SPA','TOCOPILLA','MATERIAL DE CONSTRUCCIÓN / FERRETERÍA / REPUESTOS MAQUINAS','BIENES','Antofagasta',true),
('76340983-K','SCHULER ELEKTRISCH LIMITADA','TOCOPILLA','MATERIAL DE CONSTRUCCIÓN / FERRETERÍA / REPUESTOS MAQUINAS','BIENES','Antofagasta',true)
on conflict (rut) do nothing;
